-- CreateTable
CREATE TABLE "Vessel" (
    "IMONo" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "VesselType" INTEGER NOT NULL,

    CONSTRAINT "Vessel_pkey" PRIMARY KEY ("IMONo")
);

-- CreateTable
CREATE TABLE "CE_PPSCCReferenceLine" (
    "RowID" INTEGER NOT NULL,
    "Category" TEXT NOT NULL,
    "VesselTypeID" INTEGER NOT NULL,
    "Size" TEXT NOT NULL,
    "Traj" TEXT NOT NULL,
    "a" DOUBLE PRECISION NOT NULL,
    "b" DOUBLE PRECISION NOT NULL,
    "c" DOUBLE PRECISION NOT NULL,
    "d" DOUBLE PRECISION NOT NULL,
    "e" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "CE_PPSCCReferenceLine_pkey" PRIMARY KEY ("RowID")
);

-- CreateTable
CREATE TABLE "DailyLogEmission" (
    "EID" INTEGER NOT NULL,
    "VesselID" INTEGER NOT NULL,
    "LOGID" BIGINT NOT NULL,
    "FromUTC" TIMESTAMP(3) NOT NULL,
    "TOUTC" TIMESTAMP(3) NOT NULL,
    "MET2WCO2" DOUBLE PRECISION NOT NULL,
    "AET2WCO2" DOUBLE PRECISION NOT NULL,
    "BOT2WCO2" DOUBLE PRECISION NOT NULL,
    "VRT2WCO2" DOUBLE PRECISION NOT NULL,
    "TotT2WCO2" DOUBLE PRECISION NOT NULL,
    "MEW2WCO2e" DOUBLE PRECISION NOT NULL,
    "AEW2WCO2e" DOUBLE PRECISION NOT NULL,
    "BOW2WCO2e" DOUBLE PRECISION NOT NULL,
    "VRW2WCO2e" DOUBLE PRECISION NOT NULL,
    "ToTW2WCO2" DOUBLE PRECISION NOT NULL,
    "MESox" DOUBLE PRECISION NOT NULL,
    "AESox" DOUBLE PRECISION NOT NULL,
    "BOSox" DOUBLE PRECISION NOT NULL,
    "VRSox" DOUBLE PRECISION NOT NULL,
    "TotSOx" DOUBLE PRECISION NOT NULL,
    "MENOx" DOUBLE PRECISION NOT NULL,
    "AENOx" DOUBLE PRECISION NOT NULL,
    "TotNOx" DOUBLE PRECISION NOT NULL,
    "MEPM10" DOUBLE PRECISION NOT NULL,
    "AEPM10" DOUBLE PRECISION NOT NULL,
    "TotPM10" DOUBLE PRECISION NOT NULL,
    "AERCO2T2W" DOUBLE PRECISION NOT NULL,
    "AERCO2eW2W" DOUBLE PRECISION NOT NULL,
    "EEOICO2eW2W" DOUBLE PRECISION NOT NULL,
    "CreatedAt" TIMESTAMP(3) NOT NULL,
    "UpdatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DailyLogEmission_pkey" PRIMARY KEY ("EID")
);

-- AddForeignKey
ALTER TABLE "DailyLogEmission" ADD CONSTRAINT "DailyLogEmission_VesselID_fkey" FOREIGN KEY ("VesselID") REFERENCES "Vessel"("IMONo") ON DELETE RESTRICT ON UPDATE CASCADE;
